<h1><?php echo $this->pageTitle; ?></h1>

<p><strong>Call of Duty: World at War</strong> (также известная как <strong>Call of Duty: WaW</strong>, рабочее название <strong>Call of Duty 5</strong>) (<a href="https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA" title="Русский язык">рус.</a> &laquo;Зов долга: Мир в войне&raquo;) &mdash; <a href="https://ru.wikipedia.org/wiki/%D0%9C%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%8F_%D0%B8%D0%B3%D1%80%D0%B0" title="Мультиплатформенная компьютерная игра">мультиплатформенная компьютерная игра</a>, <a href="https://ru.wikipedia.org/wiki/%D0%A8%D1%83%D1%82%D0%B5%D1%80_%D0%BE%D1%82_%D0%BF%D0%B5%D1%80%D0%B2%D0%BE%D0%B3%D0%BE_%D0%BB%D0%B8%D1%86%D0%B0" title="Шутер от первого лица">шутер от первого лица</a>, разработана <a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%A8%D0%90" title="США">американской</a> компанией <a href="https://ru.wikipedia.org/wiki/Treyarch" title="Treyarch">Treyarch</a> и издана <a href="https://ru.wikipedia.org/wiki/Activision" title="Activision">Activision</a>. Пятая игра в серии <a href="https://ru.wikipedia.org/wiki/Call_of_Duty_(%D1%81%D0%B5%D1%80%D0%B8%D1%8F_%D0%B8%D0%B3%D1%80)" title="Call of Duty (серия игр)">Call of Duty</a>, а также последняя игра, где действие происходит во время Второй мировой войны.</p>

<p>Игра Call of Duty: World at War была выпущена <a href="https://ru.wikipedia.org/wiki/11_%D0%BD%D0%BE%D1%8F%D0%B1%D1%80%D1%8F" title="11 ноября">11 ноября</a> <a href="https://ru.wikipedia.org/wiki/2008_%D0%B3%D0%BE%D0%B4_%D0%B2_%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D1%8B%D1%85_%D0%B8%D0%B3%D1%80%D0%B0%D1%85" title="2008 год в компьютерных играх">2008 года</a> на шести целевых платформах: <a href="https://ru.wikipedia.org/wiki/PlayStation_2" title="PlayStation 2">PlayStation 2</a>, <a href="https://ru.wikipedia.org/wiki/PlayStation_3" title="PlayStation 3">PlayStation 3</a>, <a href="https://ru.wikipedia.org/wiki/Xbox_360" title="Xbox 360">Xbox 360</a>, <a href="https://ru.wikipedia.org/wiki/PC" title="PC">PC</a>, <a href="https://ru.wikipedia.org/wiki/Nintendo_Wii" title="Nintendo Wii">Nintendo Wii</a> и <a href="https://ru.wikipedia.org/wiki/Nintendo_DS" title="Nintendo DS">Nintendo DS</a>. <a href="https://ru.wikipedia.org/wiki/19_%D0%BD%D0%BE%D1%8F%D0%B1%D1%80%D1%8F" title="19 ноября">19 ноября</a> <a href="https://ru.wikipedia.org/wiki/2008_%D0%B3%D0%BE%D0%B4_%D0%B2_%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D1%8B%D1%85_%D0%B8%D0%B3%D1%80%D0%B0%D1%85" title="2008 год в компьютерных играх">2008 года</a> игра стала доступна для покупки через интернет-сервис <a href="https://ru.wikipedia.org/wiki/Steam" title="Steam">Steam</a>.</p>

<p>Сюжет игры снова возвращается к действиям <a href="https://ru.wikipedia.org/wiki/%D0%92%D1%82%D0%BE%D1%80%D0%B0%D1%8F_%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%8F_%D0%B2%D0%BE%D0%B9%D0%BD%D0%B0" title="Вторая мировая война">Второй мировой войны</a> и начинается с того места, где японские солдаты захватили главного героя. Одиночная кампания содержит две стороны &mdash; одна из них американская, которая предлагает игроку повоевать с японскими солдатами, и вторая советская, которая предлагает игроку повоевать с немцами.</p>

<p>В первый же день релиза игры было продано более одного миллиона копий игры. Таким образом, игра пропустила вперед только спортивный симулятор &mdash; <a href="https://ru.wikipedia.org/wiki/FIFA_09" title="FIFA 09">FIFA 09</a>.</p>

<h2>Сюжет</h2>

<p>Миссии проходят с <a href="https://ru.wikipedia.org/wiki/1942_%D0%B3%D0%BE%D0%B4" title="1942 год">1942</a> по <a href="https://ru.wikipedia.org/wiki/1945_%D0%B3%D0%BE%D0%B4" title="1945 год">1945 год</a>. На протяжении всей сюжетной линии игра идёт за двух персонажей. Первый &mdash; это рядовой морской пехоты Миллер. Основной персонаж почти всех миссий за США (не считая только одной миссии &mdash; за старшину-пулемётчика Локка, входящего в эскадрилью &laquo;Чёрные кошки&raquo;, является третьим персонажем). Второй &mdash; это рядовой красной армии Дмитрий Петренко. Данный персонаж будет представлять СССР. Всего в игре 15 миссий.</p>

<h2>Пролог</h2>

<p>Идёт декабрь 1941 год. <a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D0%BF%D0%B0%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BD%D0%B0_%D0%9F%D1%91%D1%80%D0%BB-%D0%A5%D0%B0%D1%80%D0%B1%D0%BE%D1%80" title="Нападение на Пёрл-Харбор">Нападение на Пёрл-Харбор</a>. Самое большое несчастье в истории военно-морских сил США. Потеряна половина флота, большие жертвы. Соединённые Штаты объявляют войну Японии и начинают набирать в армию миллионы добровольцев. Организовываются разведывательные группы для рейдов на вражеские острова. Начинается постройка самолётов и танков. В первые же дни большие потери; много пропавших без вести.</p>

<h2>Развитие сюжета</h2>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Всегда готов</strong> Атолл Макин, южная часть Тихого океана,17 августа 1942 года, рядовой Миллер,2-й рейдерский батальон Морской пехоты США Рейдеры Карлсона</li>
</ul>

<p>Во время <a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B9%D0%B4_%D0%BD%D0%B0_%D0%9C%D0%B0%D0%BA%D0%B8%D0%BD" title="Рейд на Макин">рейда на атолл Макин</a> группа рядового Миллера замечена. Все попадают в плен. Группу начинает допрашивать один из японских офицеров. Но ничего не может выжать из солдат. Поэтому хочет убить их, обосновав это тем, что они бесполезны и от них ничего не добьёшься. Но Миллеру удаётся спастись &mdash; его спасает отряд морской пехоты США, под командованием сержанта Тома Салливана. Они и убивают всех японцев, продвигаясь в джунгли. Там они попутно, разрушая постовой пункт японцев, помогают 2-му отделению, которое тоже участвует в атаке. Они доходят до следующей точки, где взорвав оружейный склад с боеприпасами, уплывают на моторных лодках.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Слабое сопротивление</strong> 15 сентября 1944 года, Белый пляж, Пелелиу, рядовой Миллер, 1-я дивизия морской пехоты</li>
</ul>

<p>Начинается <a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B8%D1%82%D0%B2%D0%B0_%D0%B7%D0%B0_%D0%9F%D0%B5%D0%BB%D0%B5%D0%BB%D0%B8%D1%83" title="Битва за Пелелиу">высадка на остров Пелелиу</a>. Предпоследняя страница в ходе войны США с Японией. Рядовой Миллер под командованием того же сержанта Салливана направляется на остров Пелелиу. Во время высадки они наткнулись на камни, оказавшись под обстрелом миномётов. Но у Миллера получается выбраться оттуда. Салливан приказывает Миллеру взять рацию и вызвать удар по набережной, где расположены пулемётные гнёзда японцев. После удара войска проходят в глубь японской защиты и разрушают оставшиеся укрепления. После этого нужно захватить командный пункт. Миллер, капрал Ройбук, рядовой Полонский и сержант Том Салливан пробираются вовнутрь и зачищают бункер. После чего им придется отразить атаку танков. Но во время передышки на них нападает японский офицер и убивает катаной Тома Салливана.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Жёсткая посадка</strong> 15 сентября 1944 года,Аэродром, Пелелиу, рядовой Миллер, 1-я дивизия морской пехоты</li>
</ul>

<p>После смерти Салливана командиром становится уже сержант Ройбук. На этот раз нужно ударить по аэродрому, чтобы японцы не смогли поддерживать других солдат на острове и в случае чего не смогли предоставить авиаподдержку. Войска уничтожают японскую базу, которая мешает им добраться до аэродрома. После чего они подавляют сопротивление в здании главного командного пункта на аэродроме и направляются к траншеям и последнему укреплению, откуда ещё отчаянно ведут борьбу японцы. Но те успевают вызвать подкрепление. Миллеру и другим приходится туго, но помогает авиаподдержка, которая появляется в нужный момент по вызову солдат.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Вендетта</strong> 17 сентября 1942 года, Сталинград,СССР, рядовой Дмитрий Петренко, 62-армия</li>
</ul>

<p>Рядовой Дмитрий Петренко приходит в себя после боя в фонтане, где немецкие солдаты расстреливают раненых. Но Петренко остаётся жив и находит ещё одного выжившего &mdash; сержанта <a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B5-%D0%BA%D1%80%D0%B5%D1%81%D1%82%D1%8C%D1%8F%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%B0%D1%80%D0%BC%D0%B8%D1%8F" title="Рабоче-крестьянская Красная армия">Красной Армии</a> Виктора Резнова. Он просит помочь ему, его рука ранена, и он не может стрелять, поэтому это должен сделать Дмитрий. Нужно убить фашистского генерала Генриха Амселя. Амсель &mdash; гениальный стратег и военный преступник. Амсель приезжает, за этим наблюдают Петренко и Резнов. После этого под шум пролетающих бомбардировщиков Дмитрий убивает конвой. Потом они с Резновым бегут к разрушенному зданию, но попадают под обстрел вражеского снайпера. Убив его, они идут дальше, Резнов замечает через окно, что идёт конвой немцев и приказывает лечь Дмитрию. Но их всё равно замечает овчарка. Немцы начинают жечь здание с помощью огнемётов. Петренко и Резнову еле удаётся выбраться из горящего здания. Их выбрасывает взрывом на улицу рядом с немецким патрулём, Резнов пытается дотянуться до оружия, но его выбивают из рук. Резнова и Дмитрия спасают бойцы Красной Армии, которые собираются штурмовать связной пост. Петренко и Резнов помогают им снайперской поддержкой, но все бойцы погибают. После начинается бой на площади, генерал Амсель оказывается в ловушке. Петренко убивает убегающего генерала. После этого один из снарядов попадает в здание, где находятся главные герои. Последним шансом приходится прыжок в канал.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Их земля, их кровь</strong> 18 апреля 1945 года, <a href="https://ru.wikipedia.org/wiki/%D0%97%D0%B5%D0%B5%D0%BB%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B5_%D0%B2%D1%8B%D1%81%D0%BE%D1%82%D1%8B" title="Зееловские высоты">Зееловские высоты</a>, Германия, рядовой Дмитрий Петренко, 3-я ударная армия</li>
</ul>

<p><a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B5-%D0%BA%D1%80%D0%B5%D1%81%D1%82%D1%8C%D1%8F%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%B0%D1%80%D0%BC%D0%B8%D1%8F" title="Рабоче-крестьянская Красная армия">Красная Армия</a> ставит под контроль Зееловские высоты.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Выжигай их</strong> 15 сентября 1944 года,Белый пляж,Пелелиу, рядовой Миллер,1-я дивизия морской пехоты</li>
</ul>

<p>После того как разрушен аэродром, нужно зачистить джунгли от миномётных расчётов, чтобы смогли пройти американские танки. Под командованием того же сержанта Ройбука, Миллер выжигает все миномётные расчёты, расчищая путь.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Неумолимый</strong> 16 сентября 1944 года,Утёс,Пелелиу, рядовой Миллер,1-я дивизия морской пехоты</li>
</ul>

<p>Теперь после всего сделанного нужно полностью вытеснить противника с острова. Во время перехода по джунглям на танковую колонну нападают японцы. Половина солдат гибнет. Приходится расчищать путь вручную. После взятия точки, где находится тяжёлый пулемёт, Миллер открывает огонь по деревне, откуда ведётся командование. После подавления назначенного пункта, солдаты идут в земляные пещеры &mdash; последняя точка, где японцы всё ещё яростно сопротивляются. После зачистки пещер наконец взят остров Пелелиу.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Железом и кровью</strong> 16 апреля 1945 года,Зееловские высоты,Германия, рядовой Дмитрий Петренко,3-я ударная армия</li>
</ul>

<p>Рядовой Петренко в составе танковой дивизии атакует Зееловские высоты и лишает противника техники, танков и земляных укреплений.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Стальное кольцо</strong> 23 апреля 1945 года,Панков,Германия, рядовой Дмитрий Петренко,3-я ударная армия</li>
</ul>

<p>Петренко, под командованием Резнова и комиссара Маркова, захватывает город Панков.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Выселение</strong> 24 апреля 1945 года,Берлин,Германия, рядовой Дмитрий Петренко,3-я ударная армия</li>
</ul>

<p>Петренко с другими солдатами проводит рейд по Берлину, уничтожает немцев в последних укреплениях &mdash; метро и домах. Немцам приходится бежать, и во время побега они затопляют метро, где находятся главные герои. Кажется, что все они погибают, но они выживают и продолжают с Красной Армией взятие Берлина.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Чёрные кошки</strong> 3 апреля 1945 года,К югу от Окинавы, старшина Локк,Эскадрилья Чёрная Пиранья VPB-54</li>
</ul>

<p>В этой миссии мы играем не за рядового Миллера, а за старшину Локка, который сидит за пулемётом самолета <a href="https://ru.wikipedia.org/wiki/Consolidated_PBY_Catalina" title="Consolidated PBY Catalina">Consolidated PBY Catalina</a>. Задача &mdash; уничтожить три японских судна, поставляющих оружие японцам на Окинаву. После выполнения задачи, самолёты возвращаются на базу, но, получив сигнал SOS, летят к американскому флоту. Самолёты вступают в бой, где второй самолёт сбивают. Первый самолёт, в котором находится старшина Локк, садится и подбирает раненых с кораблей. После этого они благополучно улетают.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Взрывай и выжигай</strong> 14 мая 1945 года,Хребет Уанна,Окинава, рядовой Миллер,1-я дивизия морской пехоты</li>
</ul>

<p>Началась последняя страница в войне США с Японией. Солдаты захватывают последний опорный пункт на хребте, a там считанные мили до замка Сюри. Здесь предстоит под дождём и в условиях плохой видимости уничтожить японцев.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Точка излома</strong> 29 мая 1945 года,Замок Сюри,Окинава, рядовой Миллер,1-я дивизия морской пехоты</li>
</ul>

<p>Начинается последнее сражение. Солдаты должны захватить замок. Следует ожесточённая борьба, и японцы не хотят сдаваться. После долгих боёв Ройбук, Миллер и Полонский врываются в замок, где следуют волны японских солдат, одна за другой. После очередного взятия яруса замка, солдаты находят японских военных, которые пытаются сдаться. Ройбук и Полонский начинают их осматривать в поисках оружия, но вдруг происходит взрыв из-за того, что японец отдирает чеку у гранаты на груди (зависит от того, в кого из японцев стрелял Миллер). Погибает либо Ройбук, либо Полонский. Затем, начинается последняя японская контратака. Миллер вызывает три удара с воздуха и после этого атака прекращается. В конце Миллер получает на память жетон павшего друга Ройбука или Полонского.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Сердце Рейха</strong> 30 апреля 1945 года,Рейхстаг,Берлин, рядовой Дмитрий Петренко,150-я стрелковая дивизия</li>
</ul>

<p>После смерти своих друзей Петренко, Резнов и рядовой Чернов, которые остались живы, присоединившись к 150-й стрелковой дивизии, нападают на Рейхстаг. После долгих сражений они уничтожают всю защиту и проникают вовнутрь. Во время захвата входа в Рейхстаг, немецкий огнемётчик тяжело ранит рядового Чернова, но он выжил.</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Крах</strong> 30 апреля 1945 года,Рейхстаг-Берлин,Германия, рядовой Дмитрий Петренко,150-я стрелковая дивизия</li>
</ul>

<p>Солдаты врываются в Рейхстаг, уничтожают всех вражеских солдат и выходят на крышу, где их ждёт последняя волна сопротивляющихся немцев. После долгой битвы на крышу наносят залповый удар из &laquo;Катюш&raquo;. Петренко берёт флаг у убитого солдата, и хочет поставить его, но вдруг из-за угла выбегает немец и стреляет в Дмитрия. Резнов успевает убить его с помощью тесака и поднимает Петренко. Дмитрий ставит флаг. Война окончена.</p>

<h2>Главные персонажи</h2>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой С. Миллер</strong> &mdash; протагонист американской кампании.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Рядовой Дмитрий Петренко</strong> &mdash; протагонист кампании за СССР. Участвует в событиях игры <a href="https://ru.wikipedia.org/wiki/Call_of_Duty:_Black_Ops" title="Call of Duty: Black Ops">Call of Duty: Black Ops</a>.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Сержант Виктор Резнов</strong> &mdash; Солдат Красной Армии . Главный направляющий по игре советской кампании. Любимые фразы &mdash; &laquo;Мразь&raquo;, &laquo;Ничтожество&raquo;, &laquo;Подонки&raquo; и &laquo;Месть&raquo;. Участвует в событиях игр <a href="https://ru.wikipedia.org/wiki/Call_of_Duty:_Black_Ops" title="Call of Duty: Black Ops">Call of Duty: Black Ops</a> и <a href="https://ru.wikipedia.org/wiki/Call_of_Duty:_Black_Ops_II" title="Call of Duty: Black Ops II">Call of Duty: Black Ops II</a>. В русской версии озвучивает<a href="https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BF%D0%BF,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D1%81%D0%BB%D0%B0%D0%B2_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87" title="Копп, Владислав Владимирович">Владислав Копп</a>.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Старшина Локк</strong> &mdash; стрелок <a href="https://ru.wikipedia.org/wiki/Consolidated_PBY_Catalina" title="Consolidated PBY Catalina">самолёта</a>, входящего в эскадрилью &laquo;Чёрные кошки&raquo;.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Сержант Ройбук</strong> (&dagger; &mdash; зависит от действий игрока) &mdash; командир отряда <a href="https://ru.wikipedia.org/wiki/1-%D1%8F_%D0%B4%D0%B8%D0%B2%D0%B8%D0%B7%D0%B8%D1%8F_%D0%BA%D0%BE%D1%80%D0%BF%D1%83%D1%81%D0%B0_%D0%BC%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%B9_%D0%BF%D0%B5%D1%85%D0%BE%D1%82%D1%8B_(%D0%A1%D0%A8%D0%90)" title="1-я дивизия корпуса морской пехоты (США)">1-й дивизии морской пехоты США</a>. бывший капрал. Может погибнуть в миссии &laquo;Точка излома&raquo;.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Полонский</strong> (&dagger; &mdash; зависит от действий игрока) &mdash; Морпех <a href="https://ru.wikipedia.org/wiki/1-%D1%8F_%D0%B4%D0%B8%D0%B2%D0%B8%D0%B7%D0%B8%D1%8F_%D0%BA%D0%BE%D1%80%D0%BF%D1%83%D1%81%D0%B0_%D0%BC%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%B9_%D0%BF%D0%B5%D1%85%D0%BE%D1%82%D1%8B_(%D0%A1%D0%A8%D0%90)" title="1-я дивизия корпуса морской пехоты (США)">1-й дивизии морской пехоты США</a>. Может погибнуть в миссии &laquo;Точка излома&raquo; вместо Ройбука. Любимое слово &laquo;Дерьмо&raquo;. В русской версии озвучивает <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D1%80%D0%BE%D0%B7%D0%BE%D0%B2,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_(%D0%B0%D0%BA%D1%82%D1%91%D1%80_%D0%B4%D1%83%D0%B1%D0%BB%D1%8F%D0%B6%D0%B0)" title="Морозов, Александр (актёр дубляжа)">Александр Морозов</a>.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Сержант Том Салливан</strong> (&dagger;) &mdash; Морпех <a href="https://ru.wikipedia.org/wiki/1-%D1%8F_%D0%B4%D0%B8%D0%B2%D0%B8%D0%B7%D0%B8%D1%8F_%D0%BA%D0%BE%D1%80%D0%BF%D1%83%D1%81%D0%B0_%D0%BC%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%B9_%D0%BF%D0%B5%D1%85%D0%BE%D1%82%D1%8B_(%D0%A1%D0%A8%D0%90)" title="1-я дивизия корпуса морской пехоты (США)">1-й дивизии морской пехоты США</a>. Убит в миссии &laquo;Слабое сопротивление&raquo; во время <a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B8%D1%82%D0%B2%D0%B0_%D0%B7%D0%B0_%D0%9F%D0%B5%D0%BB%D0%B5%D0%BB%D0%B8%D1%83" title="Битва за Пелелиу">битвы за Пелелиу</a>.</li>
</ul>

<h2>Антагонисты</h2>

<ul>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <strong>Генрих Амсель</strong> (&dagger;) &mdash; нацистский генерал, &laquo;архитектор страданий Сталинграда&raquo;, по словам сержанта Резнова. Скорее всего прототипом для персонажа послужил генерал-фельдмаршал <a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D1%83%D0%BB%D1%8E%D1%81,_%D0%A4%D1%80%D0%B8%D0%B4%D1%80%D0%B8%D1%85" title="Паулюс, Фридрих">Фридрих Паулюс</a>. Резнов утверждает, что именно Амсель ответственен за чудовищные злодеяния против мирного населения, не только в Сталинграде, но и на всех оккупированных территориях Советского Союза. Убит Дмитрием Петренко.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg?uselang=ru" title="Флаг Японии"><img alt="Флаг Японии" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/22px-Flag_of_Japan.svg.png" /></a> <strong>Японский офицер</strong> (&dagger;) &mdash; допрашивает и жестоко пытает взятый в плен отряд Миллера. Убит Томом Салливаном. В русской версии озвучивает<a href="https://ru.wikipedia.org/wiki/%D0%A9%D0%B5%D1%80%D0%B1%D0%B8%D0%BD%D0%B8%D0%BD,_%D0%9E%D0%BB%D0%B5%D0%B3_%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87" title="Щербинин, Олег Григорьевич">Олег Щербинин</a>.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg?uselang=ru" title="Флаг Японии"><img alt="Флаг Японии" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/22px-Flag_of_Japan.svg.png" /></a> <strong>Японский рядовой</strong> (&dagger;) &mdash; жестоко пытает и убивает по приказу Японского офицера взятый в плен отряд Миллера. Убит Ройбуком.</li>
</ul>

<h2>Второстепенные персонажи</h2>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Комиссар Марков</strong> &mdash; <a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B5-%D0%BA%D1%80%D0%B5%D1%81%D1%82%D1%8C%D1%8F%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%B0%D1%80%D0%BC%D0%B8%D1%8F" title="Рабоче-крестьянская Красная армия">Красной Армии</a>. Участвовал во <a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%80%D0%BB%D0%B8%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%BD%D0%B0%D1%81%D1%82%D1%83%D0%BF%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F" title="Берлинская наступательная операция">взятии Берлина</a>.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Сержант Далетский</strong> (&dagger;) &mdash; <a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B5-%D0%BA%D1%80%D0%B5%D1%81%D1%82%D1%8C%D1%8F%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%B0%D1%80%D0%BC%D0%B8%D1%8F" title="Рабоче-крестьянская Красная армия">Красной Армии</a>. Участвовал в <a href="https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%B0%D0%BB%D0%B8%D0%BD%D0%B3%D1%80%D0%B0%D0%B4%D1%81%D0%BA%D0%B0%D1%8F_%D0%B1%D0%B8%D1%82%D0%B2%D0%B0" title="Сталинградская битва">обороне Сталинграда</a>. Погиб.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Рядовой Чернов</strong> &mdash; Солдат Красной Армии. Солдат-пацифист, вёл дневник про войну. По-видимому, призван в армию после 1943 г. Вооружен<a href="https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D0%BD%D1%82%D0%BE%D0%B2%D0%BA%D0%B0_%D0%9C%D0%BE%D1%81%D0%B8%D0%BD%D0%B0" title="Винтовка Мосина">трехлинейной винтовкой</a>, за плечами носит &quot;<a href="https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D1%89%D0%B5%D0%B2%D0%BE%D0%B9_%D0%BC%D0%B5%D1%88%D0%BE%D0%BA" title="Вещевой мешок">сидор</a>&quot;. В предпоследней миссии был тяжело ранен, получив ожоги 3 степени от немецкого огнеметчика у входа в Рейхстаг.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Младший Сержант Арсений</strong> (&dagger;) &mdash; солдат <a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B5-%D0%BA%D1%80%D0%B5%D1%81%D1%82%D1%8C%D1%8F%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%B0%D1%80%D0%BC%D0%B8%D1%8F" title="Рабоче-крестьянская Красная армия">Красной Армии</a>. Участвовал в <a href="https://ru.wikipedia.org/wiki/%D0%A8%D1%82%D1%83%D1%80%D0%BC_%D0%A0%D0%B5%D0%B9%D1%85%D1%81%D1%82%D0%B0%D0%B3%D0%B0" title="Штурм Рейхстага">штурме Рейхстага</a>. Должен был водрузить знамя на крыше, но погиб под пулемётным огнём. Знамя водрузил Дмитрий Петренко.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Рукер</strong> (&dagger;) &mdash; солдат 1-й дивизии морской пехоты США. Радист отряда. Участвовал в рейде на Макин. Убит, когда сработала ловушка, погиб от рук японского солдата с мечом</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Пайл</strong> (&dagger;) &mdash; солдат, член развед отряда Миллера. Захвачен в плен. После допроса зарезан ножом.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Андерсон</strong> (&dagger;) &mdash; солдат, член разведотряда Миллера. Захвачен в плен. Казнён.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой МакКорд</strong> (&dagger;) &mdash; солдат, член разведотряда Миллера. Захвачен в плен. Казнён.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Нельсон</strong> (&dagger;) &mdash; солдат, член разведотряда Миллера. Захвачен в плен. Казнён.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Кук</strong> &mdash; солдат, член разведотряда Миллера. Захвачен в плен. Спасён отрядом Салливана.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Капрал Галлахер</strong> &mdash; солдат 1-й дивизии морской пехоты США. Член отряда спасателей. Эвакуировал выживших членов отряда Миллера.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой 1-го класса Аллен</strong> &mdash; солдат 1-й дивизии морской пехоты США. Член отряда спасателей. Эвакуировал выживших членов отряда Миллера.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Райан</strong> (&dagger; &mdash; зависит от действий игрока) &mdash; солдат 1-й дивизии морской пехоты США. Участвовал в рейде на Макин. Может быть спасён игроком, но вскоре погибает.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Льютис</strong> (&dagger;) &mdash; солдат 1-й дивизии морской пехоты США. Участвовал в рейде на Макин. Был захвачен в плен. Казнён.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Капрал Лозано</strong> (&dagger;) &mdash; солдат 1-й дивизии морской пехоты США. Участвовал в рейде на Макин. Убит.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Денни</strong> &mdash; солдат 1-й дивизии морской пехоты США. Снайпер. Участвовал в рейде на Макин.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рержант Снайдер</strong> (&dagger;) &mdash; солдат 1-й дивизии морской пехоты США. Участвовал в рейде на Макин. Погиб при взрыве бочки.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Слэйбак</strong> (&dagger;) &mdash; солдат 1-й дивизии морской пехоты США. Участвовал в рейде на Макин. Погиб при взрыве бочки вместе с сержантом Снайдером.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Купман</strong> (&dagger;) &mdash; солдат 1-й дивизии морской пехоты США. Участвовал в битве за Пелелиу (миссия &laquo;Слабое сопротивление&raquo;). Убит выстрелом в голову.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Гловер</strong> &mdash; солдат 1-й дивизии морской пехоты США. Огнемётчик. Участвовал в битве за Пелелиу (миссия &laquo;Слабое сопротивление&raquo;).</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Рядовой Спрогисс</strong> &mdash; солдат 1-й дивизии морской пехоты США. Радист отряда. Участвовал в битве за Пелелиу (миссия &laquo;Слабое сопротивление&raquo;).</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Сержант Рукер</strong> &mdash; солдат 1-й дивизии морской пехоты США. Участвовал в битве за Пелелиу (миссия &laquo;Неумолимый&raquo;). Радист отряда. Передал по радио о взятии острова майору Гибсону.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Майор Гордон</strong> &mdash; командир 1-го батальона 1-й дивизии морской пехоты США. Командир штурма Пелелиу и Окинавы.</li>
</ul>

<h2>Зомби-нацисты</h2>

<p>Зомби-нацисты &mdash; бонусный режим игры, который открывается после прохождения одиночной кампании. Возможно играть как в одиночку, так и в кооперативе, с 3 другими игроками. Деньги (очки) начисляются за уничтожение зомби и починку окон, которые преграждают зомби путь к игрокам. Зомби приходят волнами, в небольших промежутках между которыми игроки могут передохнуть и укрепить свою защиту. Игра заканчивается со смертью всех игроков, так как атаки зомби повторяются бесконечно, при этом сами зомби с каждой новой атакой становятся все сильнее. Всего было выпущено 4 карты:</p>

<ul>
	<li><strong>Nacht der Untoten</strong> (<a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BC%D0%B5%D1%86%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA" title="Немецкий язык">нем.</a> &laquo;Ночь Мертвецов&raquo;) &mdash; копия бункера с японского аэродрома.</li>
	<li><strong>Verr&uuml;ckt</strong> (<a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BC%D0%B5%D1%86%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA" title="Немецкий язык">нем.</a> &laquo;Безумие&raquo;) &mdash; подобие психиатрической больницы в Берлине. Добавлены электричество и случайный выбор места появления коробок с оружием.</li>
	<li><strong>Shi no Numa</strong> (<a href="https://ru.wikipedia.org/wiki/%D0%AF%D0%BF%D0%BE%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA" title="Японский язык">яп.</a> &laquo;Болото Смерти&raquo;) &mdash; несколько хижин, стоящих на зыбкой почве. Добавлены &laquo;адские гончие, японцы зомби и Wunderwaffe DG-2<strong>. Присутствует, как и следовало ожидать, японское оружие.</strong></li>
	<li><strong>Der Riese</strong> (<a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BC%D0%B5%D1%86%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA" title="Немецкий язык">нем.</a> &laquo;Великан&raquo;) &mdash; нацистская фабрика, где велись сверхсекретные исследования. Добавлены телепорты, бомба-обезьяна, возможность улучшать своё оружие и несколько новых бонусов. Найдя и включив приёмники с записями, можно узнать о скрытой истории за этим режимом.</li>
</ul>

<p>Этот режим перешёл в <a href="https://ru.wikipedia.org/wiki/Call_of_Duty:_Black_Ops" title="Call of Duty: Black Ops">Call of Duty: Black Ops</a>, где история продолжает развиваться. У каждой карты есть своя <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%B0%D0%BB" title="Метал">&laquo;металлическая&raquo;</a> фоновая тема, которую можно прослушать, проделав некоторые определённые действия.</p>

<p>В немецкой версии, режим игры Нацистские Зомби вырезан.</p>

<p>В совместной игре, начиная с карты <strong>Shi no Numa</strong>, предоставляется возможность играть за одного из четырёх слегка &laquo;двинутых по фазе&raquo; персонажей:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:US_flag_48_stars.svg?uselang=ru" title="Соединённые Штаты Америки"><img alt="Соединённые Штаты Америки" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/22px-US_flag_48_stars.svg.png" /></a> <strong>Танк Демпси</strong>  &mdash; американский солдат. Его внешность скопирована с рядового Полонского. Любимое слово &mdash; &laquo;Дерьмо&raquo;.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <strong>Николай Белинский</strong>  &mdash; советский солдат. Скопирован с рядового Чернова. Любит водку.</li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <strong>Эдвард Рихтгофен</strong> &mdash; социопатичный и надменный нацистский доктор, отвестственный за создание зомби и адских гончих. Также является создателем Wunderwaffe DG-2. Скопирован с Генриха Амселя.</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg?uselang=ru" title="Флаг Японии"><img alt="Флаг Японии" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/22px-Flag_of_Japan.svg.png" /></a> <strong>Такео Масаки</strong> &mdash; фанатичный японский офицер. Скопирован с японского офицера, допрашивающего отряд Миллера в первом уровне Call of Duty: World at War.</li>
</ul>

<p>Есть другие персонажи</p>

<ul>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a><strong>Людвиг Максис</strong>&ndash; был немецким учёным, работавший вместе с Эдвардом над созданием зомби и адских гончих. Людвиг подарил своей дочери собаку по имени Флаффи, но случилась беда: когда пришла дочь Людвига, она увидела, что его папа и его ассистент работают над собакой Флаффи.Флаффи случайно забежала в телепорт, и все думали, что она погибла. Но она появилась в образе адской гончей. Ассистент закрыл дверь, чтобы оставить доктора и её дочь с порождением ада. Эдвард является его ассистентом.</li>
</ul>

<ul>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a><strong>Саманта Максис</strong>&ndash;Дочь Людвига.В Black Ops если выполнить пасхалку на карте &quot;Луна&quot;, то душа Саманты будет жить в теле Эдварда.</li>
</ul>

<ul>
	<li><strong>Бонусный режим</strong> &mdash; <strong>Nacht der Untoten</strong></li>
	<li><strong>Бонусный режим</strong> &mdash; <strong>Verruckt</strong></li>
	<li><strong>Бонусный режим</strong> &mdash; <strong>Shi-no-Numa</strong></li>
	<li><strong>Бонусный режим</strong> &mdash; <strong>Der Riese</strong></li>
</ul>

<h2>Оружие</h2>

<p>Винтовки с продольно-скользящим затвором и ПТР:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Springfield_M1903" title="Springfield M1903">Springfield M1903A4</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg?uselang=ru" title="Флаг Японии"><img alt="Флаг Японии" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/22px-Flag_of_Japan.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Arisaka_Type_38" title="Arisaka Type 38">Arisaka Type 38</a> (Существует в двух вариантах- со штыком и без штыка.)</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D0%BD%D1%82%D0%BE%D0%B2%D0%BA%D0%B0_%D0%9C%D0%BE%D1%81%D0%B8%D0%BD%D0%B0" title="Винтовка Мосина">Винтовка Мосина</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Mauser_98k" title="Mauser 98k">Mauser 98k</a> (В игре называется Kar98k)</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%A2%D0%A0%D0%A1-41" title="ПТРС-41">ПТРС-41</a></li>
</ul>

<p>Самозарядные винтовки, автоматы и карабины:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%92%D0%A2-40" title="СВТ-40">СВТ-40</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Gewehr_43" title="Gewehr 43">Gewehr 43</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/M1_Garand" title="M1 Garand">M1 Garand</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/StG_44" title="StG 44">StG 44</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/M1A1_Carbine" title="M1A1 Carbine">M1A1 Carbine</a></li>
</ul>

<p>Пистолеты-пулемёты:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B8%D1%81%D1%82%D0%BE%D0%BB%D0%B5%D1%82-%D0%BF%D1%83%D0%BB%D0%B5%D0%BC%D0%B5%D1%82_%D0%A2%D0%BE%D0%BC%D0%BF%D1%81%D0%BE%D0%BD%D0%B0" title="Пистолет-пулемет Томпсона">Пистолет-пулемет Томпсона</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/MP_40" title="MP 40">MP 40</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg?uselang=ru" title="Флаг Японии"><img alt="Флаг Японии" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/22px-Flag_of_Japan.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%B8%D0%BF_100_(%D0%BF%D0%B8%D1%81%D1%82%D0%BE%D0%BB%D0%B5%D1%82-%D0%BF%D1%83%D0%BB%D0%B5%D0%BC%D1%91%D1%82)" title="Тип 100 (пистолет-пулемёт)">Type 100</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%9F%D0%A8-41" title="ППШ-41">ППШ-41</a></li>
</ul>

<p>Пулемёты и автоматические винтовки:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg?uselang=ru" title="Флаг Японии"><img alt="Флаг Японии" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/22px-Flag_of_Japan.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Type_99_(%D0%BF%D1%83%D0%BB%D0%B5%D0%BC%D1%91%D1%82)" title="Type 99 (пулемёт)">Type 99</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a>/ <a href="https://ru.wikipedia.org/wiki/Browning_M1918" title="Browning M1918">Browning M1918</a> (в игре называется BAR)</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%94%D0%9F-28" title="ДП-28">ДП-28</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/MG42" title="MG42">MG42</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/FG-42" title="FG-42">FG-42</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Browning_M1919" title="Browning M1919">Browning M1919</a></li>
</ul>

<p>Пистолеты и револьверы:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/M1911" title="M1911">M1911</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg?uselang=ru" title="Флаг Японии"><img alt="Флаг Японии" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/22px-Flag_of_Japan.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D0%BC%D0%B1%D1%83_%D0%A2%D0%B8%D0%BF_14" title="Намбу Тип 14">Nambu Type 14</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Walther_P38" title="Walther P38">Walther P38</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%A2-33" title="ТТ-33">ТТ-33</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_Kingdom.svg?uselang=ru" title="Флаг Великобритании"><img alt="Флаг Великобритании" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/22px-Flag_of_the_United_Kingdom.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Webley_Revolver" title="Webley Revolver">Webley MK VI</a> (в игре называется .357 Magnum)</li>
</ul>

<p>Дробовики:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Winchester_Model_1897" title="Winchester Model 1897">Winchester Model 1897</a> (в игре называется M1897 Trench Gun)</li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%94%D0%B2%D1%83%D1%81%D1%82%D0%B2%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D1%80%D1%83%D0%B6%D1%8C%D1%91" title="Двуствольное ружьё">Двуствольное ружьё</a></li>
</ul>

<p>Гранатомёты:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%B7%D1%83%D0%BA%D0%B0" title="Базука">Базука</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BD%D1%86%D0%B5%D1%80%D1%88%D1%80%D0%B5%D0%BA" title="Панцершрек">Панцершрек</a></li>
</ul>

<p>Гранаты:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Mk_2" title="Mk 2">Mk 2</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%9B%D0%B8%D0%BF%D0%BA%D0%B0%D1%8F_%D0%B1%D0%BE%D0%BC%D0%B1%D0%B0" title="Липкая бомба">Липкая бомба</a> (в игре называется N&deg; 74 ST)</li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BA%D1%82%D0%B5%D0%B9%D0%BB%D1%8C_%D0%9C%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B2%D0%B0" title="Коктейль Молотова">Коктейль Молотова</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union.svg?uselang=ru" title="Флаг СССР"><img alt="Флаг СССР" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%93%D0%94-33" title="РГД-33">РГД-33</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/Stielhandgranate" title="Stielhandgranate">Stielhandgranate</a></li>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_Japan.svg?uselang=ru" title="Флаг Японии"><img alt="Флаг Японии" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/22px-Flag_of_Japan.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%B8%D0%BF_97_(%D0%B3%D1%80%D0%B0%D0%BD%D0%B0%D1%82%D0%B0)" title="Тип 97 (граната)">Type 97</a> (в игре называется Kiska)</li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%94%D1%8B%D0%BC%D0%BE%D0%B2%D0%B0%D1%8F_%D0%B3%D1%80%D0%B0%D0%BD%D0%B0%D1%82%D0%B0" title="Дымовая граната">Дымовая граната</a></li>
	<li>Газ-табун</li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%B3%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%BA%D0%B5%D1%82%D0%B0" title="Сигнальная ракета">Сигнальная ракета</a></li>
</ul>

<p>Огнемёты:</p>

<ul>
	<li><a href="https://commons.wikimedia.org/wiki/File:Flag_of_the_United_States.svg?uselang=ru" title="Флаг США"><img alt="Флаг США" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png" /></a> <a href="https://ru.wikipedia.org/wiki/M2_(%D0%BE%D0%B3%D0%BD%D0%B5%D0%BC%D1%91%D1%82)" title="M2 (огнемёт)">M2</a></li>
</ul>

<p>Чудесное оружие (доступно только в режиме &quot;Зомби&quot;):</p>

<ul>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> Ray Gun (также, имеется на уровне &quot;Слабое сопротивление&quot; как <a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D1%81%D1%85%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D1%8F%D0%B9%D1%86%D0%BE_(%D0%B2%D0%B8%D1%80%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5)" title="Пасхальное яйцо (виртуальное)">пасхальное яйцо</a>).</li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%BB%D0%B0%D0%B3_%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%B3%D0%BE_%D1%80%D0%B5%D0%B9%D1%85%D0%B0" title="Флаг Третьего рейха"><img alt="Красный флаг, в центре которого находится белый круг с чёрной свастикой" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_German_Reich_%281935%E2%80%931945%29.svg/22px-Flag_of_German_Reich_%281935%E2%80%931945%29.svg.png" /></a> Wunderwaffe DG-2</li>
	<li>Бомба-обезьянка</li>
	<li>Нож Боуи</li>
</ul>

<h2>Изменения в немецкой версии игры</h2>

<ul>
	<li>Из игры была убрана вся <a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%B2%D0%B0%D1%81%D1%82%D0%B8%D0%BA%D0%B0" title="Свастика">свастика</a> и заменена на <a href="https://ru.wikipedia.org/wiki/%D0%96%D0%B5%D0%BB%D0%B5%D0%B7%D0%BD%D1%8B%D0%B9_%D0%BA%D1%80%D0%B5%D1%81%D1%82" title="Железный крест">железный крест</a>.</li>
	<li>В миссии &laquo;Их земля, их кровь&raquo; в вступительной заставке было заменено изображение Гитлера.</li>
	<li>Все расистские выражения которые присутствовали в английской версии были переозвучены.</li>
	<li>Из игры была вырезана излишняя жестокость не только в советской кампании.</li>
	<li>В миссии &laquo;Их земля, их кровь&raquo; в английской версии миссия начиналась в небольшом помещении, где Дмитрий был в плену, затем помещение штурмует Резнов, герою был предоставлен выбор: казнить или помиловать немцев, затем Дмитрий выходил на улицу; в немецкой версии начало действия миссии начиналось сразу на улице.</li>
	<li>Из игры были вырезаны все плакаты с нацистской пропагандой.</li>
	<li>Дополнительный уровень &laquo;Нацистские зомби&raquo; был полностью вырезан.</li>
</ul>

<h3>Мультиплеерное вооружение</h3>

<p>В мультиплеере к каждому индивидуальному оружию предусмотрены соответствующие улучшения. Возможно выбрать только одно из максимально возможных четырёх. Это не относится к пистолетам.</p>

<h2>Многопользовательская игра</h2>

<p>Кроме стандартного мультиплеера, в игре имеется и кооператив: режим &laquo;Зомби-нацисты&raquo; и кооперативное прохождение на четверых игроков. В кооперативном прохождении игроки проходят основную кампанию синглплеера (за исключением двух миссий: &laquo;Вендетта&raquo; и &laquo;Чёрные кошки&raquo;). Игроки во время прохождения могут соревноваться между собой, зарабатывая очки. Также во время прохождения будут доступны чит-карты, которые можно применить во время прохождения кампании. Их можно найти во время прохождения игры по одной на каждом уровне. Call of Duty: World at War &mdash; единственная игра из серии Call of Duty, в которой присутствует кооперативное прохождение основной кампании (исключение: режим &laquo;Спецоперации&raquo; (англ. &laquo;Special Ops&raquo;) в игре Call of Duty: Modern Warfare 2 и Call of Duty: Modern Warfare 3).</p>

<h2>Коллекционное издание</h2>

<p>Российское коллекционное издание включает в себя: металлизированный чехол с выпуклым тиснением, DVD-диск с игрой, полное руководство пользователя на русском языке, двухсторонний плакат формата А3 и один из четырёх видов медальона &mdash; в виде пули, дракона, креста или сапёрной лопатки. В западной версии игры в комплекте с коллекционным изданием поставляется код для сетевой игры, который даёт возможность использовать автоматическую винтовку <a href="https://ru.wikipedia.org/wiki/FG-42" title="FG-42">FG-42</a> вне зависимости от уровня игрока.</p>

<h2>Отзывы</h2>

<p>Игра заняла третье место в номинации &laquo;Шутер года&raquo; (2008) журнала <a href="https://ru.wikipedia.org/wiki/%D0%98%D0%B3%D1%80%D0%BE%D0%BC%D0%B0%D0%BD%D0%B8%D1%8F_(%D0%B6%D1%83%D1%80%D0%BD%D0%B0%D0%BB)" title="Игромания (журнал)">Игромания</a>.<sup><a href="https://ru.wikipedia.org/wiki/Call_of_Duty:_World_at_War#cite_note-1">1</a></sup></p>

<p>В целом игра получила менее положительные оценки, нежели прошлая игры серии <a href="https://ru.wikipedia.org/wiki/Call_of_Duty_4:_Modern_Warfare" title="Call of Duty 4: Modern Warfare">Call of Duty 4: Modern Warfare</a>, которую разработала компания <a href="https://ru.wikipedia.org/wiki/Infinity_Ward" title="Infinity Ward">Infinity Ward</a>.</p>

<h2>Интересные факты</h2>

<ul>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D0%BB%D1%8C_%D0%A2%D0%BE%D1%80%D0%BE,_%D0%93%D0%B8%D0%BB%D1%8C%D0%B5%D1%80%D0%BC%D0%BE" title="Дель Торо, Гильермо">Гильермо дель Торо</a> &mdash; большой поклонник серии игр Call of Duty, а его любимой игрой из всей серии является Call of Duty: World at War, на втором месте идут игры серии Modern Warfare.</li>
	<li>В миссии &laquo;Вендетта&raquo; на форме Резнова видны погоны, но погоны были введены в <a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B5-%D0%BA%D1%80%D0%B5%D1%81%D1%82%D1%8C%D1%8F%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%B0%D1%80%D0%BC%D0%B8%D1%8F" title="Рабоче-крестьянская Красная армия">Красной Армии</a> только в 1943 году, а действие миссии происходит в 1942 году. К тому же, у Резнова видны знаки различия и на петлицах &mdash; 3 эмалевых треугольника, что соответствует старшему сержанту, а не сержанту (2 эмалевых треугольника).</li>
	<li>Аналогичный ляп: у комиссара Маркова видны знаки различия на петлицах, но они были упразднены в <a href="https://ru.wikipedia.org/wiki/1943_%D0%B3%D0%BE%D0%B4" title="1943 год">1943 году</a>. К тому же звание комиссар было упразднено в <a href="https://ru.wikipedia.org/wiki/1942_%D0%B3%D0%BE%D0%B4" title="1942 год">1942 году</a>.</li>
	<li>В игре большое несовпадение дат &mdash; <a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B8%D1%82%D0%B2%D0%B0_%D0%B7%D0%B0_%D0%9E%D0%BA%D0%B8%D0%BD%D0%B0%D0%B2%D1%83" title="Битва за Окинаву">захват Окинавы</a> произошёл <a href="https://ru.wikipedia.org/wiki/21_%D0%B8%D1%8E%D0%BD%D1%8F" title="21 июня">21 июня</a> <a href="https://ru.wikipedia.org/wiki/1945_%D0%B3%D0%BE%D0%B4" title="1945 год">1945 года</a>, а в игре <a href="https://ru.wikipedia.org/wiki/29_%D0%BC%D0%B0%D1%8F" title="29 мая">29 мая</a> <a href="https://ru.wikipedia.org/wiki/1945_%D0%B3%D0%BE%D0%B4" title="1945 год">1945 года</a>.</li>
	<li>Call of Duty: World at War вторая игра серии после Call of Duty: United Offensive, где применён огнемёт.</li>
	<li>Call of Duty: World at War последняя игра в серии Call of Duty, где в многопользовательской игре присутствует техника (впервые техника в сетевой игре появилась в Call of Duty: United Offensive, а потом в Call of Duty 3).</li>
	<li>Call of Duty: World at War первая игра в серии Call of Duty, где появился режим Зомби.</li>
	<li>В миссии &laquo;Слабое сопротивление&raquo;, если на пляже после бомбардировки пойти в самую правую точку, а затем развернуться и прыгнуть в каждую из трёх ям с водой по очереди, оставшись в третьей, то земля начнёт трястись, раздастся звук гонга и странные голоса (на японском). Через несколько секунд из земли вылезут четыре статуи в форме львов. У них в зубах будет лучевое оружие.</li>
	<li>Если с помощью огнемёта поджечь жертву, то под конец она будет похожа на зомби.</li>
	<li>Во время боя можно слышать, как японские солдаты говорят фразы на немецком языке.</li>
	<li>В начале миссии &laquo;Вендетта&raquo; рядовой Дмитрий Петренко встречает снайпера сержанта Резнова &mdash; этот момент тесно связан с фильмом &laquo;<a href="https://ru.wikipedia.org/wiki/%D0%92%D1%80%D0%B0%D0%B3_%D1%83_%D0%B2%D0%BE%D1%80%D0%BE%D1%82" title="Враг у ворот">Враг у ворот</a>&raquo;, где главный герой <a href="https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B9%D1%86%D0%B5%D0%B2,_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D0%B9_%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87" title="Зайцев, Василий Григорьевич">Василий Зайцев</a> встречает комиссара в том же фонтане, который пытается убить немецкого полковника, после помогает ему в этом.</li>
	<li>На протяжении всей игры рядовой Чернов почему-то носит генеральский ремень.</li>
	<li>Из игры была вырезана британская кампания. В игровых файлах обнаружено вырезанное британское оружие, кроме того, в сетевой игре есть липкая граната, которой нет ни в одной из кампаний.</li>
	<li>В миссии &laquo;Всегда готов&raquo; можно спасти рядового по фамилии Райан. Это намёк на фильм Стивена Спилберга &mdash; &laquo;<a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B0%D1%81%D1%82%D0%B8_%D1%80%D1%8F%D0%B4%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE_%D0%A0%D0%B0%D0%B9%D0%B0%D0%BD%D0%B0" title="Спасти рядового Райана">Спасти рядового Райана</a>&raquo;. Отсылкой к этому фильму также является начало миссии &laquo;Слабое сопротивление&raquo;.</li>
	<li>В игре у пистолета <a href="https://ru.wikipedia.org/wiki/M1911" title="M1911">Кольт М1911</a> боезапас 8 патронов, хотя в реальности 7.</li>
	<li>В советской кампании ПТРС-41 представлено как снайперская винтовка. На самом деле, это противотанковое ружьё.</li>
	<li>Немецкие солдаты отдают генералу честь по образцу союзников.</li>
</ul>
