<h1><?php echo $this->pageTitle; ?></h1>

<p><em><strong>В тылу врага 2</strong></em>&nbsp;(<a href="https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA" title="Английский язык">англ.</a>&nbsp;<em>Faces of War</em>&nbsp;в издании&nbsp;<a href="https://ru.wikipedia.org/wiki/Ubisoft" title="Ubisoft">Ubisoft</a>)&nbsp;&mdash;&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%8F_%D0%B8%D0%B3%D1%80%D0%B0" title="Компьютерная игра">компьютерная игра</a>&nbsp;в жанре&nbsp;<a href="https://ru.wikipedia.org/wiki/Action" title="Action">action</a>&nbsp;/&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_%D0%B2_%D1%80%D0%B5%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%BC_%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%B8" title="Стратегия в реальном времени">RTS</a>, разработанная компанией&nbsp;<a href="https://ru.wikipedia.org/wiki/Best_Way" title="Best Way">Best Way</a>&nbsp;и изданная компанией&nbsp;<a href="https://ru.wikipedia.org/wiki/1%D0%A1" title="1С">1С</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/8_%D1%81%D0%B5%D0%BD%D1%82%D1%8F%D0%B1%D1%80%D1%8F" title="8 сентября">8 сентября</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/2006_%D0%B3%D0%BE%D0%B4" title="2006 год">2006&nbsp;года</a>.</p>

<h2>Игровые кампании</h2>

<p>Игра делится на три кампании: кампанию за Германию, англоамериканскую кампанию, кампанию за СССР. В каждой кампании по десять миссий (три из которых&nbsp;&mdash; тренировочные, одинаковы во всех кампаниях). Оставшиеся 7 миссий делятся на три обычных и четыре более сложных миссии. Также в каждой кампании, после прохождения всех миссий, открывается последняя и самая сложная миссия.</p>

<p><strong>Кампания за Германию</strong></p>

<p><strong>1.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%B9%D0%BC%D0%B5%D0%B3%D0%B5%D0%BD" title="Неймеген">Неймегенский</a>&nbsp;мост</strong>&nbsp;(Неймеген, сентябрь&nbsp;<a href="https://ru.wikipedia.org/wiki/1944_%D0%B3%D0%BE%D0%B4" title="1944 год">1944 года</a>).&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D0%9C%D0%B0%D1%80%D0%BA%D0%B5%D1%82-%D0%93%D0%B0%D1%80%D0%B4%D0%B5%D0%BD" title="Операция Маркет-Гарден">В связи с наступлением союзников</a>, немецкое командование предпринимает решение послать группу диверсантов и бойцов прикрытия, чтобы взорвать мост в Неймегене и приостановить наступление союзников. Немецкому отряду удаётся выполнить операцию, но чтобы сесть на катера у пристани, им нужно уничтожить баржу. Они пробиваются через парк и захватывают отремонтированный танк&nbsp;<a href="https://ru.wikipedia.org/wiki/T34_(%D0%A0%D0%A1%D0%97%D0%9E)" title="T34 (РСЗО)">Шерман (Каллиопа)</a>&nbsp;с ракетной установкой, с помощью которого взрывают баржу и уплывают из Неймегена. Однако если игрок заблаговременно перетащит одно из 88-мм британских орудий через мост, то он может не прорываться через парк, а подорвать баржу с этого орудия и сразу идти к катерам.</p>

<p><strong>2.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D0%BB%D1%8C%D1%86" title="Вильц">Вильц</a></strong>&nbsp;(Вильц, 16 декабря 1944 года).&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%90%D1%80%D0%B4%D0%B5%D0%BD%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F_(1945)" title="Арденнская операция (1945)">Немцы начинают наступление</a>. Начав стремительный прорыв англоамериканских оборонительных позиций, передовые немецкие роты оказались втянуты в бой за Вильц со 110-й пехотной дивизией американцев. К немцам приходит подкрепление в виде тяжёлой САУ&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%AF%D0%B3%D0%B4%D1%82%D0%B8%D0%B3%D1%80" title="Ягдтигр">Ягдтигр</a>, и им удаётся захватить город и заставить американцев сдаться.</p>

<p><strong>3. Стомон</strong>&nbsp;(Стомон, 19 декабря 1944 года). Немецкие фольксгренадеры начинают штурм Стомона. К ним на помощь подоспевают танки&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BD%D1%82%D0%B5%D1%80%D0%B0_(%D1%82%D0%B0%D0%BD%D0%BA)" title="Пантера (танк)">Пантера</a>&nbsp;и&nbsp;<a href="https://ru.wikipedia.org/wiki/PzKpfw_IV" title="PzKpfw IV">PzKpfw IV</a>, с помощью которых немцы захватывают площадь возле городской церкви и спасают своих офицеров из плена.</p>

<p><strong>4. Клёрф</strong>&nbsp;(окрестности реки Клёрф, 17 декабря 1944 года). Чтобы ослабить оборону американцев и&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%90%D1%80%D0%B4%D0%B5%D0%BD%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F_(1945)" title="Арденнская операция (1945)">облегчить немецким частям наступление</a>, группа солдат проникает в один из американских военных складов в районе реки Клерф, уничтожает его, захватывает танки и начинает наступление на оборонительные позиции американцев возле железнодорожного моста. Когда обороны у американцев в районе больше нету, к группе на помощь подоспевают парашютисты Мильтке. Они пытаются взорвать мост динамитом, но у них ничего не выходит. На их счастье подоспевает локомотив с цистернами топлива. Захватив его, немцы выводят его на середину моста, находят в одном из вагонов авиабомбы и подрывают их. В итоге мост и склад уничтожены.</p>

<p><strong>5. Марвье</strong>&nbsp;(окрестности&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%81%D1%82%D0%BE%D0%BD%D1%8C" title="Бастонь">Бастони</a>, 19 декабря 1944 года). Командование&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D1%80%D0%BC%D0%B0%D1%85%D1%82" title="Вермахт">Вермахта</a>&nbsp;предпринимает решение&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%81%D1%82%D0%BE%D0%BD%D1%81%D0%BA%D0%BE%D0%B5_%D1%81%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5" title="Бастонское сражение">захватить Бастонь</a>&nbsp;и посылает отряд из танков Пантера и PzKpfw IV и нескольких пехотинцев захватить Марвье&nbsp;&mdash; важный перекресток дорог в районе Бастони. В деревне обороняются отряды&nbsp;<a href="https://ru.wikipedia.org/wiki/101-%D1%8F_%D0%B2%D0%BE%D0%B7%D0%B4%D1%83%D1%88%D0%BD%D0%BE-%D0%B4%D0%B5%D1%81%D0%B0%D0%BD%D1%82%D0%BD%D0%B0%D1%8F_%D0%B4%D0%B8%D0%B2%D0%B8%D0%B7%D0%B8%D1%8F_(%D0%A1%D0%A8%D0%90)" title="101-я воздушно-десантная дивизия (США)">101-й воздушно-десантной дивизии</a>&nbsp;американцев. Немцы подавляют сопротивление врага и продвигаются к перекрёстку, откуда им предстоит уничтожить идущие колонны танков из 10-й американской бронетанковой дивизии.</p>

<p><strong>6.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%94%D0%B8%D0%BD%D0%B0%D0%BD_(%D0%91%D0%B5%D0%BB%D1%8C%D0%B3%D0%B8%D1%8F)" title="Динан (Бельгия)">Динан</a></strong>&nbsp;(Динан, 25 декабря 1944 года). После провала немцев захватить мосты в&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D0%BC%D1%8E%D1%80" title="Намюр">Намюре</a>, они начинают двигаться к Динану&nbsp;&mdash; единственному мосту через&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B0%D1%81" title="Маас">Маас</a>. Преодолев сопротивление врага, немцы всё же переправляют свои танки через реку. (Данная миссия имеет несоответствие с историей, так как на самом деле немцы не смогли даже дойти до Мааса. Несоответствие с историей (скорее, соответствие с немецкими планами) также имеют миссии &laquo;Рошфор&raquo; и &laquo;Лувен&raquo;.)</p>

<p><strong>7.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%BE%D1%88%D1%84%D0%BE%D1%80" title="Рошфор">Рошфор</a></strong>&nbsp;(американская топливная база недалеко от Рошфора, декабрь 1944 года). После форсирования Мааса на первый план у немецкого командования выходит вопрос о нехватке топлива для танков. По плану, топливо должно было быть захвачено на американских и английских топливных складах в Арденнах. На один из таких складов, в Рошфоре, посылают двух переодетых диверсантов. Те, действуя с максимальной осторожностью, уговаривают машиниста-немца послужить Рейху и переправить локомотив с топливом к &laquo;своим&raquo;. После того, как база захватывается немецким отрядом, а машинист увозит топливо к немцам, начинается оборона базы. Выстояв против превосходящих сил противника, немцы вздыхают с облегчением и готовятся к решительному броску на&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D1%82%D0%B2%D0%B5%D1%80%D0%BF%D0%B5%D0%BD" title="Антверпен">Антверпен</a>.</p>

<p><strong>8.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9B%D1%83%D0%B2%D0%B5%D0%BD" title="Лувен">Лувен</a></strong>&nbsp;(окрестности Антверпена, 17 января&nbsp;<a href="https://ru.wikipedia.org/wiki/1945_%D0%B3%D0%BE%D0%B4" title="1945 год">1945 года</a>) (открывается после прохождения остальных миссий за Германию). После успешных операций в Рошфоре и Динане, немцы начинают наступление на Антверпен&nbsp;&mdash; конечную цель операции &laquo;Стража на Рейне&raquo;. Преодолев с большим трудом линии обороны американцев, немецкие пехотные и танковые соединения 17 января занимают Лувен, а 20 января берут Антверпен.</p>

<p><strong>Кампания за СССР</strong></p>

<p><strong>1.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9B%D1%8E%D0%B1%D0%BB%D0%B8%D0%BD" title="Люблин">Люблин</a></strong>&nbsp;(Люблин, июль 1944 года). Перед советскими отрядами, несущими большие потери в боях за Люблин, ставится задача&nbsp;&mdash; найти польских повстанцев и их руководителя, генерала Грабовски. Советские солдаты находят полевой штаб повстанцев и, увидев, что генерала там нету, решают вместе с восставшими поляками атаковать немецкий опорный пункт в одном из городских дворов. Справившись с немцами, под руинами угла дома советские солдаты и польские повстанцы находят генерала Грабовски.</p>

<p><strong>2. Вернуть документы</strong>&nbsp;(<a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BD%D0%B4%D0%BE%D0%BC%D0%B8%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BF%D0%BB%D0%B0%D1%86%D0%B4%D0%B0%D1%80%D0%BC" title="Сандомирский плацдарм">Сандомирский плацдарм</a>, 13 августа 1944 года). Идут тяжёлые бои на&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9B%D1%8C%D0%B2%D0%BE%D0%B2%D1%81%D0%BA%D0%BE-%D0%A1%D0%B0%D0%BD%D0%B4%D0%BE%D0%BC%D0%B8%D1%80%D1%81%D0%BA%D0%B0%D1%8F_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F" title="Львовско-Сандомирская операция">Львове-Сандомире</a>&nbsp;После того, как выясняется что один из офицеров&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%9A%D0%9A%D0%90" title="РККА">РККА</a>&nbsp;&mdash; &laquo;капитан Леонов&raquo;&nbsp;&mdash; перебежчик, укравший из штаба важные документы, касающиеся предстоящего наступления,&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%9C%D0%95%D0%A0%D0%A8" title="СМЕРШ">СМЕРШ</a>&nbsp;решает не допустить попадания этих документов в руки немецких офицеров и посылает отряд разведчиков-пехотинцев за реку, в прифронтовую полосу, чтобы те выкрали документы у немецкого<a href="https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D0%B5%D1%80-%D0%BB%D0%B5%D0%B9%D1%82%D0%B5%D0%BD%D0%B0%D0%BD%D1%82" title="Обер-лейтенант">обер-лейтенанта</a>&nbsp;Краусса. Здесь отряду предстоит уничтожить немецкие миномёты, чтобы получить в помощь мотострелковый отряд, а затем и танки, отбить немецкие контратаки, убить Краусса и захватить документы, а после уничтожить неприятельский заслон, мешающий беспрепятственному отходу солдат.</p>

<p><strong>3. Крепость</strong>&nbsp;(<a href="https://ru.wikipedia.org/wiki/%D0%93%D0%BB%D0%BE%D0%B3%D0%B0%D1%83" title="Глогау">Глогау</a>, 1 апреля 1945 года). В ходе&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D1%81%D0%BB%D0%BE-%D0%9E%D0%B4%D0%B5%D1%80%D1%81%D0%BA%D0%B0%D1%8F_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F" title="Висло-Одерская операция">Висло-Одерской операции</a>, штаб&nbsp;<a href="https://ru.wikipedia.org/wiki/1-%D0%B9_%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D1%84%D1%80%D0%BE%D0%BD%D1%82" title="1-й Украинский фронт">1-го Украинского фронта</a>&nbsp;отдаёт приказ о штурме практически неприступной цитадели Глогау. После преодоления советскими пехотинцами сопротивления немцев на подступах к крепости, советские самоходные гаубицы&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%98%D0%A1%D0%A3-152" title="ИСУ-152">ИСУ-152</a>&nbsp;пробивают брешь в одной из стен крепости, куда и устремляются советские пехотинцы. Подавив сопротивление на первом ярусе, они позже захватывают сооружения на втором ярусе. В конце концов, советские войска проникают на территорию последнего яруса, где подавляют сопротивление немцев и захватывают в плен руководителя обороны цитадели&nbsp;&mdash; Оливера Вагнера.</p>

<p><strong>4.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%97%D0%B5%D0%BB%D0%BE%D0%B2" title="Зелов">Зееловский вокзал</a></strong>&nbsp;(Зелов, апрель 1945 года).&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%97%D0%B5%D0%B5%D0%BB%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B5_%D0%B2%D1%8B%D1%81%D0%BE%D1%82%D1%8B" title="Зееловские высоты">После успешного наступления на Зееловских высотах</a>, советские пехотинцы устремляются на Зеелов. В данной миссии игроку предстоит прорвать немецкую оборону возле вокзала в Зеелове и захватить все неприятельские оборонительные линии.</p>

<p><strong>5. Атака с фланга</strong>&nbsp;(район &laquo;высоты 153&raquo;, Германия, 19 апреля 1945 года). После захвата Зееловских высот, один из советских танковых батальонов остановился около хорошо укреплённой &laquo;высоты 153&raquo;. Зная, что захватить высоту лобовой атакой невозможно, советский моторизованный отряд посылают во фланговую атаку. По пути отряд попадает в засаду, но всё же отбивает атаки и от двух других советских солдат, захвативших в плен немецкого офицера узнаёт, что рядом располагается<a href="https://ru.wikipedia.org/w/index.php?title=%D0%A1%D0%BA%D0%BB%D0%B0%D0%B4_%D0%B1%D0%BE%D0%B5%D0%BF%D1%80%D0%B8%D0%BF%D0%B0%D1%81%D0%BE%D0%B2&amp;action=edit&amp;redlink=1" title="Склад боеприпасов (страница отсутствует)">склад боеприпасов</a>. Отряду удаётся взорвать склад и отбить атаку немецких танков. В конце концов, отряд вместе с танкистами &laquo;сметают&raquo; немцев с высоты.</p>

<p><strong>6.&nbsp;<a href="https://ru.wikipedia.org/w/index.php?title=%D0%9D%D0%B5%D0%B9%D0%B5%D0%BD%D1%85%D0%B0%D0%B3%D0%B5%D0%BD&amp;action=edit&amp;redlink=1" title="Нейенхаген (страница отсутствует)">Нейенхаген</a></strong>&nbsp;(окрестности Нейенхагена, апрель 1945 года). Чтобы помочь штабу бригады, попавшему в беду и измотать немецкие тылы, советское командование решает начать наступление на немцев в районе Нейенхагена. В начале отряд доставляет свою штабную машину на высоту, откуда передаются координаты наступления. Далее отряд присоединяется к другим частям и те вместе отбивают немецкие контратаки, и сами готовятся к контрудару.</p>

<p><strong>7. Берлинский вокзал</strong>&nbsp;(<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%80%D0%BB%D0%B8%D0%BD" title="Берлин">Берлин</a>, 28-29 апреля 1945 года). 23 апреля 1945 года советские войска начинают&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B8%D1%82%D0%B2%D0%B0_%D0%B7%D0%B0_%D0%91%D0%B5%D1%80%D0%BB%D0%B8%D0%BD" title="Битва за Берлин">бои за Берлин</a>. В боях за Лертер&nbsp;&mdash; главный вокзал города, и мост Мольтке&nbsp;&mdash; наиболее важный мост через реку Шпрее и предстоит поучаствовать игроку. После тяжёлых боёв советские штурмовые части захватывают вокзал и мост, и отбивают немецкую контратаку.</p>

<p><strong>8.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A8%D1%82%D1%83%D1%80%D0%BC_%D0%A0%D0%B5%D0%B9%D1%85%D1%81%D1%82%D0%B0%D0%B3%D0%B0" title="Штурм Рейхстага">Рейхстаг</a></strong>&nbsp;(<a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B9%D1%85%D1%81%D1%82%D0%B0%D0%B3_(%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)" title="Рейхстаг (здание)">Рейхстаг</a>, Берлин, 1 мая 1945 года) (открывается после прохождения остальных миссий за СССР). Советские войска, после захвата моста Мольтке начинают штурм Рейхстага. Несмотря на хорошо укреплённые немецкие позиции и непрерывные немецкие контратаки, советские войска всё же водружают знамя победы над Рейхстагом.</p>

<p><strong>Кампания за союзников</strong></p>

<p><strong>1.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B4%D0%B0%D1%80" title="Радар">Радар</a></strong>&nbsp;(<a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%BE%D1%80%D0%BC%D0%B0%D0%BD%D0%B4%D0%B8%D1%8F" title="Нормандия">Нормандия</a>, май 1944 года). Союзники готовят&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%BE%D1%80%D0%BC%D0%B0%D0%BD%D0%B4%D1%81%D0%BA%D0%B0%D1%8F_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F_(1944)" title="Нормандская операция (1944)">высадку в Нормандию</a>. Прежде чем десантные катера и корабли начнут подплывать к берегу, а самолёты союзников&nbsp;&mdash; бомбить побережье, передовой диверсионный отряд тайком высаживается возле одного из радаров, уничтожает его охрану, давая возможность американскому инженеру осмотреть и взорвать радар, а после&nbsp;&mdash; выбив немцев из соседней фермы возле электростанции, уничтожить и станцию. В конце концов, отряду предстоит пробиться сквозь вражеский заслон у пляжа и уплыть на десантных катерах.</p>

<p><strong>2.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%BB%D0%B5%D0%B7_(%D0%9A%D0%B0%D0%BB%D1%8C%D0%B2%D0%B0%D0%B4%D0%BE%D1%81)" title="Фалез (Кальвадос)">Фалез</a></strong>&nbsp;(кварталы города Фалез, август 1944 года). Для того, чтобы полностью окружить немецкую&nbsp;<a href="https://ru.wikipedia.org/wiki/7-%D1%8F_%D0%B0%D1%80%D0%BC%D0%B8%D1%8F_(%D0%93%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B8%D1%8F)" title="7-я армия (Германия)">7-ю армию</a>&nbsp;и соединиться с канадскими частями, американским войскам остаётся лишь&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%BB%D0%B5%D0%B7%D1%81%D0%BA%D0%B0%D1%8F_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F" title="Фалезская операция">захватить Фалез</a>&nbsp;и 19 августа они переходят в атаку. Игроку в данной миссии предстоит захватить городские кварталы и соединиться с канадскими штурмовыми частями, чтобы затем сообща вытеснить немцев из города.</p>

<p><strong>3.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%92%D0%B0%D0%BB%D1%8C%D1%85%D0%B5%D1%80%D0%B5%D0%BD" title="Вальхерен">Вальхерен</a></strong>&nbsp;(остров Вальхерен, ноябрь 1944 года). В сентябре войска союзников берут порт Антверпен, но не могут его использовать из-за немецких орудий, расположенных на островах в устье&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A8%D0%B5%D0%BB%D1%8C%D0%B4%D0%B0" title="Шельда">реки Шельды</a>. Чтобы покончить с этим, союзники начинают масштабный морской десант на эти острова. Игроку предстоит принять участие в десанте на один из этих островов&nbsp;&mdash; Вальхерен, где ему сначала надо будет высадиться и закрепиться в низине, после достичь входа на второй ярус, а далее&nbsp;&mdash; уничтожить все прибрежные корабельные орудия и&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%94%D0%9E%D0%A2" title="ДОТ">ДОТы</a>.</p>

<p><strong>4.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B0%D1%81%D1%82%D1%80%D0%B8%D1%85%D1%82" title="Маастрихт">Маастрихт</a></strong>&nbsp;(юг&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D0%BB%D0%BB%D0%B0%D0%BD%D0%B4%D0%B8%D1%8F" title="Голландия">Голландии</a>, июль 1944 года). Не имея возможности бомбардировать&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9B%D0%BE%D0%BD%D0%B4%D0%BE%D0%BD" title="Лондон">Лондон</a>&nbsp;авиацией, немцы начинают пускать по городу батареи ракет&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%90%D0%A3-2" title="ФАУ-2">ФАУ-2</a>. Дабы прекратить дальнейшие бомбардировки, командование союзников посылает в тыл к немцам отряд с задачей&nbsp;&mdash; выкрасть документации о ФАУ-2, чтобы знать о месте их дислокации и уничтожать ракеты ещё на марше. Отряд уничтожает немецкий оборонительный гарнизон, разыскивает документацию и уплывает на&nbsp;<a href="https://ru.wikipedia.org/wiki/Landing_Vehicle_Tracked" title="Landing Vehicle Tracked">танке-амфибии</a>&nbsp;прямо из под носа немецких частей из соседних гарнизонов.</p>

<p><strong>5.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%80%D0%B0%D0%BD%D1%88" title="Авранш">Авранш</a></strong>&nbsp;(Франция, июль 1944 года). Чтобы пройти к Фалезу и Мортену, союзникам необходимо захватить мосты через реки Се и Селюн. Острие их удара направлено на Авранш: игроку предстоит принять участие в этом важном сражении, сокрушив немецкие позиции по обе стороны от моста.</p>

<p><strong>6.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%B5%D0%BD-%D0%9B%D0%B0%D0%BC%D0%B1%D0%B5%D1%80_(%D0%9A%D0%B0%D0%BB%D1%8C%D0%B2%D0%B0%D0%B4%D0%BE%D1%81)" title="Сен-Ламбер (Кальвадос)">Сен-Ламбер</a></strong>&nbsp;(август 1944 года). Англо-канадские и американские войска почти соединились у&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%BB%D0%B5%D0%B7_(%D0%9A%D0%B0%D0%BB%D1%8C%D0%B2%D0%B0%D0%B4%D0%BE%D1%81)" title="Фалез (Кальвадос)">Фалеза</a>. Одна из этих групп встречает канадцев, охраняющих церковь, переоборудованную под госпиталь. Американцы, которыми руководит игрок, остаются и отражают атаки немцев на церковь, дожидаясь подхода союзных войск.</p>

<p><strong>7.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%81%D1%82%D0%BE%D0%BD%D1%8C" title="Бастонь">Бастонь</a></strong>&nbsp;(декабрь 1944 года). Игроку предстоит удержать Бастонь от атаки превосходящих сил противника, причём, помимо обычных штурмов, немцы&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%81%D1%82%D0%BE%D0%BD%D1%81%D0%BA%D0%BE%D0%B5_%D1%81%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5" title="Бастонское сражение">пытаются отрезать</a>&nbsp;американцев от продовольствия, выдают себя за прорвавшихся к городу англичан, и, наконец, начинают всеобщий штурм. Игроку предстоит остановить его до подхода основных сил американцев.</p>

<p><strong>8. Омаха Бич</strong>&nbsp;(<a href="https://ru.wikipedia.org/wiki/%D0%9D%D0%BE%D1%80%D0%BC%D0%B0%D0%BD%D0%B4%D0%B8%D1%8F" title="Нормандия">Нормандия</a>, июнь 1944 года). Американские войска высаживаются на пляже&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9E%D0%BC%D0%B0%D1%85%D0%B0-%D0%B1%D0%B8%D1%87" title="Омаха-бич">Омаха-бич</a>&nbsp;сектора &laquo;Изи Грин&raquo; в Нормандии. Им предстоит сломить сопротивление противника у побережья, выдержать контрудар, а затем, отбивая возможные контратаки, прорваться к городу и захватить его.</p>

<p>Сценарий игры создан известным русским писателем&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%97%D0%BE%D1%80%D0%B8%D1%87" title="Александр Зорич">Александром Зоричем</a>.</p>

<h2>Оружие и техника, использующиеся в игре</h2>

<h3><a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%A1%D0%A1%D0%A0" title="СССР">СССР</a></h3>

<ul>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B8%D1%81%D1%82%D0%BE%D0%BB%D0%B5%D1%82_%D0%A2%D0%A2" title="Пистолет ТТ">Пистолет ТТ</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B2%D0%BE%D0%BB%D1%8C%D0%B2%D0%B5%D1%80_%D0%9D%D0%B0%D0%B3%D0%B0%D0%BD%D0%B0" title="Револьвер Нагана">Револьвер Нагана</a>&nbsp;и его вариант с глушителем</li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D0%BD%D1%82%D0%BE%D0%B2%D0%BA%D0%B0_%D0%9C%D0%BE%D1%81%D0%B8%D0%BD%D0%B0" title="Винтовка Мосина">Винтовка Мосина</a>&nbsp;и её снайперский вариант</li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%9F%D0%A8-41" title="ППШ-41">ППШ-41</a></li>
	<li>Ручной пулемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%94%D0%9F_(%D0%BF%D1%83%D0%BB%D0%B5%D0%BC%D1%91%D1%82)" title="ДП (пулемёт)">ДП</a></li>
	<li>Танковый пулемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%94%D0%A2_(%D0%BF%D1%83%D0%BB%D0%B5%D0%BC%D1%91%D1%82)" title="ДТ (пулемёт)">ДТ</a></li>
	<li>Ручной противотанковый гранатомёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%B7%D1%83%D0%BA%D0%B0" title="Базука">Базука</a></li>
	<li>Огнемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A4%D0%9E%D0%93-2" title="ФОГ-2">ФОГ-2</a></li>
	<li>Станковый пулемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%94%D0%A1-39" title="ДС-39">ДС-39</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/82-%D0%BC%D0%BC_%D0%BC%D0%B8%D0%BD%D0%BE%D0%BC%D1%91%D1%82_%D0%91%D0%9C-37" title="82-мм миномёт БМ-37">82-мм миномёт БМ-37</a></li>
	<li>Противотанковая пушка&nbsp;<a href="https://ru.wikipedia.org/wiki/76-%D0%BC%D0%BC_%D0%B4%D0%B8%D0%B2%D0%B8%D0%B7%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BF%D1%83%D1%88%D0%BA%D0%B0_%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D1%86%D0%B0_1942_%D0%B3%D0%BE%D0%B4%D0%B0_(%D0%97%D0%98%D0%A1-3)" title="76-мм дивизионная пушка образца 1942 года (ЗИС-3)">ЗИС-3</a></li>
	<li>Гаубица&nbsp;<a href="https://ru.wikipedia.org/wiki/152-%D0%BC%D0%BC_%D0%B3%D0%B0%D1%83%D0%B1%D0%B8%D1%86%D0%B0_%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D1%86%D0%B0_1943_%D0%B3%D0%BE%D0%B4%D0%B0_(%D0%94-1)" title="152-мм гаубица образца 1943 года (Д-1)">Д-1</a></li>
</ul>

<p>Техника</p>

<ul>
	<li>Грузовик&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%97%D0%98%D0%A1-5_(%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C)" title="ЗИС-5 (автомобиль)">ЗИС-5</a></li>
	<li>Мотоцикл&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9C-72_(%D0%BC%D0%BE%D1%82%D0%BE%D1%86%D0%B8%D0%BA%D0%BB)" title="М-72 (мотоцикл)">М-72</a></li>
	<li>Бронеавтомобиль&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%90-11" title="БА-11">БА-11</a></li>
	<li>Бронетранспортёр&nbsp;<a href="https://ru.wikipedia.org/wiki/M2_(%D0%B1%D1%80%D0%BE%D0%BD%D0%B5%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82%D1%91%D1%80)" title="M2 (бронетранспортёр)">M2</a></li>
	<li>Минный тральщик на шасси&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A2-34" title="Т-34">Т-34</a></li>
	<li>Танк артиллерийской поддержки&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%A2-7%D0%90" title="БТ-7А">БТ-7А</a></li>
	<li>Средний танк&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A2-34" title="Т-34">Т-34</a>&nbsp;и его модификация с 85-мм пушкой&nbsp;<a href="https://ru.wikipedia.org/wiki/T-34-85" title="T-34-85">T-34-85</a></li>
	<li>Тяжелый танк&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9A%D0%92-85" title="КВ-85">КВ-85</a></li>
	<li>Тяжелый танк&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%98%D0%A1-2" title="ИС-2">ИС-2</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%85%D0%BE%D0%B4%D0%BD%D0%BE-%D0%B0%D1%80%D1%82%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%D0%B8%D0%B9%D1%81%D0%BA%D0%B0%D1%8F_%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0" title="Самоходно-артиллерийская установка">САУ</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%A3-85" title="СУ-85">СУ-85</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%85%D0%BE%D0%B4%D0%BD%D0%BE-%D0%B0%D1%80%D1%82%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%D0%B8%D0%B9%D1%81%D0%BA%D0%B0%D1%8F_%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0" title="Самоходно-артиллерийская установка">САУ</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%98%D0%A1%D0%A3-152" title="ИСУ-152">ИСУ-152</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%93%D0%B2%D0%B0%D1%80%D0%B4%D0%B5%D0%B9%D1%81%D0%BA%D0%B8%D0%B9_%D1%80%D0%B5%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D1%8B%D0%B9_%D0%BC%D0%B8%D0%BD%D0%BE%D0%BC%D1%91%D1%82" title="Гвардейский реактивный миномёт">Гвардейский реактивный миномёт</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%9C-13" title="БМ-13">БМ-13</a>&nbsp;&laquo;<a href="https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%82%D1%8E%D1%88%D0%B0_(%D0%BE%D1%80%D1%83%D0%B6%D0%B8%D0%B5)" title="Катюша (оружие)">Катюша</a>&raquo;</li>
</ul>

<h3><a href="https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D1%82%D0%B8%D0%B9_%D0%A0%D0%B5%D0%B9%D1%85" title="Третий Рейх">Третий Рейх</a></h3>

<ul>
	<li><a href="https://ru.wikipedia.org/wiki/Mauser_98k" title="Mauser 98k">Карабин Маузер 98k</a>&nbsp;и его снайперский вариант</li>
	<li>Пистолет&nbsp;<a href="https://ru.wikipedia.org/wiki/Walther_P38" title="Walther P38">Walther P38</a></li>
	<li>Пистолет-пулемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/MP_38/40" title="MP 38/40">MP 38/40</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A8%D1%82%D1%83%D1%80%D0%BC%D0%BE%D0%B2%D0%B0%D1%8F_%D0%B2%D0%B8%D0%BD%D1%82%D0%BE%D0%B2%D0%BA%D0%B0" title="Штурмовая винтовка">Штурмовая винтовка</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/MP-44" title="MP-44">MP-44</a></li>
	<li>Одноразовый гранатомёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BD%D1%86%D0%B5%D1%80%D1%84%D0%B0%D1%83%D1%81%D1%82" title="Панцерфауст">Панцерфауст</a></li>
	<li>Ручной противотанковый гранатомёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BD%D1%86%D0%B5%D1%80%D1%88%D1%80%D0%B5%D0%BA" title="Панцершрек">Панцершрек</a></li>
	<li>Осколочная граната&nbsp;<a href="https://ru.wikipedia.org/wiki/Stielhandgranate" title="Stielhandgranate">Stielhandgranate</a>&nbsp;(М-24)</li>
	<li>Станковый пулемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/MG-34" title="MG-34">MG-34</a></li>
	<li>Ручной пулемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/MG-42" title="MG-42">MG-42</a></li>
	<li>Зенитная установка&nbsp;<a href="https://ru.wikipedia.org/w/index.php?title=2_cm_Flak_30/38/Flakvierling&amp;action=edit&amp;redlink=1" title="2 cm Flak 30/38/Flakvierling (страница отсутствует)">Flakvierling 38</a></li>
	<li>Миномёт&nbsp;<a href="https://ru.wikipedia.org/wiki/Kurzer_8_cm_Granatwerfer_42" title="Kurzer 8 cm Granatwerfer 42">Sgrw 42</a></li>
	<li>Противотанковая пушка&nbsp;<a href="https://ru.wikipedia.org/wiki/Pak_40" title="Pak 40">Pak 40</a></li>
	<li>Гаубица&nbsp;<a href="https://ru.wikipedia.org/wiki/15_cm_sFH_18" title="15 cm sFH 18">sFH 150-мм</a></li>
</ul>

<p>Техника</p>

<ul>
	<li>Грузовой автомобиль&nbsp;<a href="https://ru.wikipedia.org/wiki/Opel_Blitz" title="Opel Blitz">Opel Blitz</a>&nbsp;3.6</li>
	<li>Мотоцикл BMW R12</li>
	<li>Бронеавтомобиль&nbsp;<a href="https://ru.wikipedia.org/wiki/Sd.Kfz.234" title="Sd.Kfz.234">Sd.Kfz.234</a></li>
	<li>Бронетранспортёр&nbsp;<a href="https://ru.wikipedia.org/wiki/Sd_Kfz_251" title="Sd Kfz 251">Sd Kfz 251</a>/1</li>
	<li>Минный тральщик на шасси танка&nbsp;<a href="https://ru.wikipedia.org/wiki/PzKpfw_III" title="PzKpfw III">PzKpfw III</a></li>
	<li>Модифицированный легкий танк&nbsp;<a href="https://ru.wikipedia.org/wiki/PzKpfw_II" title="PzKpfw II">PzKpfw II</a>&nbsp;Ausf L &laquo;Лухс&raquo;</li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%97%D0%B5%D0%BD%D0%B8%D1%82%D0%BD%D0%B0%D1%8F_%D1%81%D0%B0%D0%BC%D0%BE%D1%85%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F_%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0" title="Зенитная самоходная установка">ЗСУ</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/Wirbelwind" title="Wirbelwind">Wirbelwind</a></li>
	<li>Средний танк&nbsp;<a href="https://ru.wikipedia.org/wiki/PzKpfw_III" title="PzKpfw III">PzKpfw III</a>&nbsp;N</li>
	<li>Тяжелый танк&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BD%D1%82%D0%B5%D1%80%D0%B0_(%D1%82%D0%B0%D0%BD%D0%BA)" title="Пантера (танк)">PzKpfw V</a>&nbsp;&laquo;Пантера&raquo;</li>
	<li>Тяжелый танк&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%B8%D0%B3%D1%80_(%D1%82%D0%B0%D0%BD%D0%BA)" title="Тигр (танк)">PzKpfw VI Ausf. E</a>&nbsp;&laquo;Тигр&raquo;</li>
	<li>Тяжелый танк&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%B8%D0%B3%D1%80_II" title="Тигр II">PzKpfw VI Ausf. B</a>&nbsp;&laquo;Королевский Тигр&raquo;</li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%85%D0%BE%D0%B4%D0%BD%D0%BE-%D0%B0%D1%80%D1%82%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%D0%B8%D0%B9%D1%81%D0%BA%D0%B0%D1%8F_%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0" title="Самоходно-артиллерийская установка">САУ</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/StuG_IV" title="StuG IV">StuG IV</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%85%D0%BE%D0%B4%D0%BD%D0%BE-%D0%B0%D1%80%D1%82%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%D0%B8%D0%B9%D1%81%D0%BA%D0%B0%D1%8F_%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0" title="Самоходно-артиллерийская установка">САУ</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%AF%D0%B3%D0%B4%D1%82%D0%B8%D0%B3%D1%80" title="Ягдтигр">PzKpfw VI Jagdtiger</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0_%D0%B7%D0%B0%D0%BB%D0%BF%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE_%D0%BE%D0%B3%D0%BD%D1%8F" title="Реактивная система залпового огня">РСЗО</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/15cm_Panzerwerfer_42_Auf.Sf" title="15cm Panzerwerfer 42 Auf.Sf">Panzerwerfer</a></li>
</ul>

<h3>Союзники</h3>

<ul>
	<li>Пистолет-пулемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9F%D0%B8%D1%81%D1%82%D0%BE%D0%BB%D0%B5%D1%82-%D0%BF%D1%83%D0%BB%D0%B5%D0%BC%D1%91%D1%82_%D0%A2%D0%BE%D0%BC%D0%BF%D1%81%D0%BE%D0%BD%D0%B0" title="Пистолет-пулемёт Томпсона">M1928A1 &laquo;Томпсон&raquo;</a></li>
	<li>Пистолет-пулемёт М3 (у инженера в миссии &laquo;Радар&raquo;)</li>
	<li>Самозарядная винтовка&nbsp;<a href="https://ru.wikipedia.org/wiki/M1_Garand" title="M1 Garand">M1 Garand</a></li>
	<li>Ручной пулемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/Bren" title="Bren">Bren</a></li>
	<li>Автоматическая винтовка&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D1%80%D0%B0%D1%83%D0%BD%D0%B8%D0%BD%D0%B3_M1918" title="Браунинг M1918">Браунинг M1918</a></li>
	<li>Ручной противотанковый гранатомёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%B7%D1%83%D0%BA%D0%B0" title="Базука">Базука</a></li>
	<li>Винтовка&nbsp;<a href="https://ru.wikipedia.org/wiki/Springfield_M1903" title="Springfield M1903">Springfield M1903</a>&nbsp;и её снайперский вариант</li>
	<li>Винтовка&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9B%D0%B8-%D0%AD%D0%BD%D1%84%D0%B8%D0%BB%D0%B4_1904" title="Ли-Энфилд 1904">Rifle NO. 4 Mk 1</a></li>
	<li>Станковый пулемёт&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%91%D1%80%D0%B0%D1%83%D0%BD%D0%B8%D0%BD%D0%B3_M2" title="Браунинг M2">Браунинг M2</a></li>
	<li>Зенитное орудие&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%AD%D1%80%D0%BB%D0%B8%D0%BA%D0%BE%D0%BD" title="Эрликон">Oerlikon 20-mm</a></li>
	<li>Миномёт М1</li>
	<li>Противотанковая пушка&nbsp;<a href="https://ru.wikipedia.org/wiki/3-%D0%B4%D1%8E%D0%B9%D0%BC%D0%BE%D0%B2%D0%B0%D1%8F_%D0%BF%D1%83%D1%88%D0%BA%D0%B0_M5" title="3-дюймовая пушка M5">M5</a></li>
	<li>Противотанковая пушка на круговом лафете&nbsp;<a href="https://ru.wikipedia.org/wiki/QF_25_pounder" title="QF 25 pounder">QF 25 pounder</a></li>
	<li>Гаубица CWT BL 152-mm</li>
	<li>Гаубица&nbsp;<a href="https://ru.wikipedia.org/wiki/155_mm_Howitzer_M114" title="155 mm Howitzer M114">155 mm Howitzer M114</a></li>
</ul>

<p>Техника</p>

<ul>
	<li>Грузовой автомобиль&nbsp;<a href="https://ru.wikipedia.org/wiki/Studebaker_US6" title="Studebaker US6">Studebaker US6</a></li>
	<li>Автомобиль&nbsp;<a href="https://ru.wikipedia.org/wiki/Willys_MB" title="Willys MB">Willys MB</a></li>
	<li>Бронеавтомобиль&nbsp;<a href="https://ru.wikipedia.org/wiki/M8_(%D0%B1%D1%80%D0%BE%D0%BD%D0%B5%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C)" title="M8 (бронеавтомобиль)">M8</a></li>
	<li>Бронетранспортёр&nbsp;<a href="https://ru.wikipedia.org/wiki/M2_(%D0%B1%D1%80%D0%BE%D0%BD%D0%B5%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82%D1%91%D1%80)" title="M2 (бронетранспортёр)">M2A1</a></li>
	<li>Минный тральщик M4A3 Crab на шасси танка&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A8%D0%B5%D1%80%D0%BC%D0%B0%D0%BD_(%D1%82%D0%B0%D0%BD%D0%BA)" title="Шерман (танк)">M4A3</a></li>
	<li>Легкий танк M8 Scott</li>
	<li>Зенитная установка на шасси танка&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%83%D1%81%D0%B5%D0%B9%D0%B4%D0%B5%D1%80" title="Крусейдер">Крусейдер</a></li>
	<li>Средний танк&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D0%BE%D0%BC%D0%B2%D0%B5%D0%BB%D1%8C_(%D1%82%D0%B0%D0%BD%D0%BA)" title="Кромвель (танк)">Mk VIII</a></li>
	<li>Средний танк&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A8%D0%B5%D1%80%D0%BC%D0%B0%D0%BD_(%D1%82%D0%B0%D0%BD%D0%BA)" title="Шерман (танк)">M4A2</a></li>
	<li>Средний танк&nbsp;<a href="https://ru.wikipedia.org/wiki/Sherman_Firefly" title="Sherman Firefly">M4A4</a></li>
	<li>Пехотный танк&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%A7%D0%B5%D1%80%D1%87%D0%B8%D0%BB%D0%BB%D1%8C_(%D1%82%D0%B0%D0%BD%D0%BA)" title="Черчилль (танк)">Mk IV &laquo;Черчилль&raquo;</a></li>
	<li>Тяжелый танк&nbsp;<a href="https://ru.wikipedia.org/wiki/M26_(%D1%82%D0%B0%D0%BD%D0%BA)" title="M26 (танк)">M26 &laquo;Першинг&raquo;</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BC%D0%BE%D1%85%D0%BE%D0%B4%D0%BD%D0%BE-%D0%B0%D1%80%D1%82%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%D0%B8%D0%B9%D1%81%D0%BA%D0%B0%D1%8F_%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0" title="Самоходно-артиллерийская установка">САУ</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/M36_(%D0%A1%D0%90%D0%A3)" title="M36 (САУ)">M36</a></li>
	<li>Сверхтяжелый штурмовой танк&nbsp;<a href="https://ru.wikipedia.org/wiki/Tortoise_(%D1%82%D0%B0%D0%BD%D0%BA)" title="Tortoise (танк)">A39</a></li>
	<li><a href="https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0_%D0%B7%D0%B0%D0%BB%D0%BF%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE_%D0%BE%D0%B3%D0%BD%D1%8F" title="Реактивная система залпового огня">РСЗО</a>&nbsp;<a href="https://ru.wikipedia.org/wiki/T34_(%D0%A0%D0%A1%D0%97%D0%9E)" title="T34 (РСЗО)">Sherman Calliope</a></li>
</ul>

<h3>Прочая техника</h3>

<ul>
	<li>Трактор &laquo;<a href="https://ru.wikipedia.org/wiki/%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B0%D0%BB_(%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BE%D1%80)" title="Универсал (трактор)">Universal-1</a>&raquo;</li>
</ul>
